Improve C ABI struct change error handling (#2386)
Over in https://github.com/NVIDIA/cuvs/pull/2369 I saw this C ABI change error 

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.15/x64/bin/check-c-abi", line 6, in <module>
    sys.exit(main_cli())
using dlpack from /home/runner/work/cuvs/cuvs/dlpack/include
             ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.15/x64/lib/python3.11/site-packages/check_c_abi/main.py", line 136, in main_cli
    errors = analyze_c_abi(old_abi, new_abi)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.15/x64/lib/python3.11/site-packages/check_c_abi/abi.py", line 351, in analyze_c_abi
    errors.extend(_analyze_struct_abi(old_abi, new_abi))
  File "/opt/hostedtoolcache/Python/3.11.15/x64/lib/python3.11/site-packages/check_c_abi/abi.py", line 293, in _analyze_struct_abi
    new_struct.members,
    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'new_struct' where it is not associated with a value
```

This PR adds a `continue` so we avoid any unbounded variables.

Authors:
  - James Bourbeau (https://github.com/jrbourbeau)
  - Corey J. Nolet (https://github.com/cjnolet)

Approvers:
  - Corey J. Nolet (https://github.com/cjnolet)
  - Gil Forsyth (https://github.com/gforsyth)

URL: https://github.com/NVIDIA/cuvs/pull/2386